services:
  youtube-monitor:
    build:
      context: .
      dockerfile: projects/services/ingestion/youtube/web/streamlit/Dockerfile
    container_name: youtube-monitor
    command:
      - "streamlit"
      - "run"
      - "/opt/airflow/projects/services/ingestion/youtube/web/streamlit/streamlit_app.py"
      - "--server.port"
      - "8502"
      - "--server.address"
      - "0.0.0.0"
    ports:
      - "8502:8502"
    env_file:
      - ./projects/services/ingestion/youtube/.env
    environment:
      - PYTHONPATH=/opt/airflow
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/projects:/opt/airflow/projects
    networks:
      - airflow_default

networks:
  airflow_default:
    external: true
