services:
  location-monitor:
    build:
      context: .
      dockerfile: projects/services/processing/tasks/location_extraction/streamlit/Dockerfile
    container_name: location-monitor
    command:
      - "streamlit"
      - "run"
      - "/opt/airflow/projects/services/processing/tasks/location_extraction/streamlit/streamlit_app.py"
      - "--server.port"
      - "8150"
      - "--server.address"
      - "0.0.0.0"
    ports:
      - "8150:8150"
    env_file:
      - ./projects/services/processing/tasks/location_extraction/.env
    environment:
      - PYTHONPATH=/opt/airflow
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/projects:/opt/airflow/projects
    networks:
      - default

networks:
  default:
    name: airflow_default
    external: true
