version: '3.8'
services:
  intention-monitor:
    build:
      context: .
      dockerfile: projects/services/processing/tasks/intention/streamlit/Dockerfile
    container_name: inetention-monitor
    command:
      - "streamlit"
      - "run"
      - "/opt/airflow/projects/services/processing/tasks/intention/streamlit/streamlit_app.py"
      - "--server.port"
      - "8503"
      - "--server.address"
      - "0.0.0.0"
    ports:
      - "8503:8503"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=airflow
      - DB_USER=airflow
      - DB_PASSWORD=airflow
      - PYTHONPATH=/opt/airflow
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/projects:/opt/airflow/projects
    # depends_on:
    #   postgres:
    #     condition: service_healthy